version: '2'
services:
  novnc:  
    image: psharkey/novnc:latest
    environment:
      # Adjust to your screen size
      - DISPLAY_WIDTH=1024
      - DISPLAY_HEIGHT=768
    ports:
      - "4280:8080"
      - "4242:4242"
      - "4243:4243"
    networks:
      - x11
networks:
  x11:
